angular.module('terrys-today-skills', [])
    .controller('SkillsController', function () {
        var skill = this;
        skill.list = [
            { id: '0001', cid: '0001', category: 'Language', name: 'Java', level: '5' },
            { id: '0002', cid: '0001', category: 'Language', name: 'C#', level: '2' },
            { id: '0003', cid: '0001', category: 'Language', name: 'Ruby', level: '2' },
            { id: '0004', cid: '0001', category: 'Language', name: 'Shell Script', level: '2' },
            { id: '0005', cid: '0001', category: 'Language', name: 'HTML5', level: '2' },
            { id: '0006', cid: '0001', category: 'Language', name: 'CSS3', level: '2' },
            { id: '0007', cid: '0001', category: 'Language', name: 'Java Script', level: '2' },
            { id: '0008', cid: '0001', category: 'Language', name: 'Objective C', level: '2' },
            { id: '0009', cid: '0001', category: 'Language', name: 'R', level: '2' },
            { id: '0010', cid: '0002', category: 'Design', name: 'UML', level: '3' },
            { id: '0011', cid: '0002', category: 'Design', name: 'ERD', level: '2' },
            { id: '0012', cid: '0003', category: 'Operating System', name: 'AIX', level: '4' },
            { id: '0013', cid: '0003', category: 'Operating System', name: 'LINUX', level: '4' },
            { id: '0014', cid: '0004', category: 'Application Server', name: 'WebSphere Application Server', level: '5' },
            { id: '0015', cid: '0004', category: 'Application Server', name: 'Tomcat', level: '3' },
            { id: '0016', cid: '0005', category: 'Web Server', name: 'Apache HTTP Server', level: '3' },
            { id: '0017', cid: '0006', category: 'Messaging', name: 'WebSphere MQ', level: '5' },
            { id: '0018', cid: '0007', category: 'DBMS', name: 'MySQL', level: '3' },
            { id: '0019', cid: '0007', category: 'DBMS', name: 'MSSQL', level: '2' },
            { id: '0020', cid: '0008', category: 'Test', name: 'JUnit', level: '5' },
            { id: '0021', cid: '0008', category: 'Test', name: 'Cucumber', level: '3' },
            { id: '0022', cid: '0008', category: 'Test', name: 'HTTPUnit', level: '3' },
            { id: '0023', cid: '0009', category: 'SCM', name: 'CVS', level: '3' },
            { id: '0024', cid: '0009', category: 'SCM', name: 'SVN', level: '3' },
            { id: '0025', cid: '0009', category: 'SCM', name: 'Git', level: '4' },
            { id: '0028', cid: '0009', category: 'SCM', name: 'Bitbucket', level: '2' },
            { id: '0026', cid: '0010', category: 'Automation', name: 'Jenkins', level: '5' },
            { id: '0027', cid: '0010', category: 'Automation', name: 'Capistrano', level: '3' },
            { id: '0029', cid: '0010', category: 'Automation', name: 'Continuous Integration', level: '5' },
            { id: '0030', cid: '0010', category: 'Automation', name: 'Continuous Delivery', level: '3' },
            { id: '0031', cid: '0011', category: 'Methodology', name: 'PDCA', level: '5' },
            { id: '0032', cid: '0011', category: 'Methodology', name: 'TDD', level: '5' },
            { id: '0033', cid: '0011', category: 'Methodology', name: 'BDD', level: '3' },
            { id: '0034', cid: '0011', category: 'Methodology', name: 'Waterfall', level: '5' },
            { id: '0035', cid: '0012', category: 'Platform', name: 'GSuite', level: '3' },
            { id: '0036', cid: '0012', category: 'Platform', name: 'Salesforce.com', level: '3' },
            { id: '0037', cid: '0012', category: 'Platform', name: 'AWS', level: '3' },
            { id: '0038', cid: '0013', category: 'Product', name: 'Gluegent Gate', level: '5' },
            { id: '0039', cid: '0013', category: 'Product', name: 'Gluegent Flow', level: '3' },
            { id: '0040', cid: '0013', category: 'Product', name: 'Gluegent Shared Address Book', level: '3' },
            { id: '0041', cid: '0013', category: 'Product', name: 'Gluegent Group Scheduler', level: '3' },
            { id: '0042', cid: '0080', category: 'Human Language', name: 'Japanese', level: '5' },
            { id: '0043', cid: '0080', category: 'Human Language', name: 'English', level: '5' },
            { id: '0044', cid: '0099', category: 'Other', name: 'Document Writing', level: '5' },
            { id: '0045', cid: '0099', category: 'Other', name: 'Consultation', level: '3' },
            { id: '0046', cid: '0099', category: 'Other', name: 'Customer Support', level: '5' },
            { id: '0047', cid: '0014', category: 'Framework', name: 'Bootstrap', level: '2' },
            { id: '0048', cid: '0014', category: 'Framework', name: 'Angular JS', level: '2' },
            { id: '0049', cid: '0014', category: 'Framework', name: 'JavaEE', level: '5' },
            { id: '0050', cid: '0013', category: 'Product', name: 'Eclipse', level: '5' },

        ];
    });